/* ------------------------------------------------------------------
   Key vocabulary — every term in the course, by unit.

   Taken from Vicky's Key_Vocabulary.docx. These definitions are pitched
   higher than the word chips inside the decks: the chips are A1–A2, for
   reading off a projector mid-lesson, while these are for revision
   afterwards, and they name the critics and the works.

   Two things were repaired on the way in, and are worth knowing about
   if her document is ever re-imported:
     · Unit 9 defined "Closed-Circuit Video" twice. The fuller entry,
       the one naming TV Buddha and the Corridor series, is the one kept.
     · Unit 2's "Grattage," carried a stray comma in the headword.
   ------------------------------------------------------------------ */

const VOCAB = [
  {
    n: 1, dir: 'week02',
    title: 'The Beginning of Modern Art',
    zh: '現代藝術的開端：藝術是如何開始改變的？',
    terms: [
      { en: 'Classical period',
        def: 'In art history, the period of art from ancient Greece and Rome, later revived as a standard of harmony, proportion, and idealized form during the Renaissance and Neoclassicism; modern movements such as Cubism and Fauvism explicitly broke from this classical standard of beauty.',
        zh: '古典時期',
        zhDef: '在藝術史中，指古希臘、羅馬的藝術時期，其和諧、比例與理想化形式的標準，後來在文藝復興與新古典主義時期被重新奉為典範；現代藝術運動如立體主義、野獸派，則明確地背離了這種古典的美的標準。' },
      { en: 'Modernism',
        def: 'In art history, the period of "formal beauty" running roughly from Realism (c.1850) to Abstract Expressionism (c.1960); for Clement Greenberg, an art that uses a discipline\'s own methods to critique and thereby entrench that discipline.',
        zh: '現代主義',
        zhDef: '在藝術史中，指大約從寫實主義（約1850年）到抽象表現主義（約1960年）的「形式美」時期；對格林伯格而言，則是一種運用該學科自身方法進行自我批判、藉此鞏固該學科本身的藝術。' },
      { en: 'Contemporary Art',
        def: 'Not simply "the art of right now," but, per Arthur Danto, a period after the end of any single unifying grand narrative in art — "a style of using styles" rather than a style itself.',
        zh: '當代藝術',
        zhDef: '並非單純指「當下的藝術」，而是根據丹托的說法，指任何單一、統合性的宏大敘事終結之後的時期──「一種運用多種風格的風格」，而非某一種風格本身。' },
      { en: 'Postmodernism',
        def: 'Not a historical period following "modern," but a mode of thought defined in opposition to the modern worldview.',
        zh: '後現代主義',
        zhDef: '並非緊接在「現代」之後的歷史分期，而是一種與現代世界觀相對立而定義的思維模式。' },
      { en: 'Formalism',
        def: 'An emphasis on form over content in art, literature, or philosophy; in art history, the critical tradition (associated with Greenberg) that traces a line from Cézanne through Picasso to Pollock.',
        zh: '形式主義',
        zhDef: '在藝術、文學或哲學中強調形式重於內容；在藝術史上，指（與格林伯格相關的）批評傳統，其脈絡由塞尚經畢卡索延伸至帕洛克。' },
      { en: 'The Aura',
        def: 'Walter Benjamin\'s term (from The Work of Art in the Age of Mechanical Reproduction, 1936) for the unique, "here-and-now" presence of an original artwork, which he argued disappears through mechanical reproduction.',
        zh: '靈光',
        zhDef: '班雅明的用語（出自《機械複製時代的藝術作品》，1936年），指原作獨一無二、「此時此地」的存在感，他認為這種靈光會因機械複製而消失。' },
      { en: 'Daguerreotype',
        def: 'An early photographic process (introduced 1839 by Louis Daguerre) that produced a single, highly detailed image on a silvered copper plate; its arrival is often cited as a key reason painting turned away from pure documentation of appearances and toward form, color, and idea.',
        zh: '銀版攝影法',
        zhDef: '一種早期的攝影技術（1839年由達蓋爾發明），在鍍銀的銅板上產生單一、細節極為清晰的影像；攝影術的出現常被視為繪畫轉而遠離單純記錄外貌、轉向形式、色彩與觀念的重要原因之一。' },
      { en: 'The End of Art',
        def: 'A recurring claim in aesthetics, made in different senses by Hegel (1817), Hans Belting (1983), and Arthur Danto (1984); generally refers not to art literally ceasing, but to the exhaustion of a particular narrative or type of art.',
        zh: '藝術的終結',
        zhDef: '美學中反覆出現的一種論點，黑格爾（1817年）、貝爾廷（1983年）與丹托（1984年）各自賦予不同意涵；一般而言，並非指藝術實際上停止存在，而是指某種特定敘事或藝術類型的窮盡。' },
      { en: 'Post-historical Art',
        def: 'Arthur Danto\'s term for art after the "end of art," in which no single grand narrative can any longer govern artistic development.',
        zh: '後歷史藝術',
        zhDef: '丹托用來指稱「藝術終結」之後的藝術的術語，此時已不再有單一的宏大敘事能夠支配藝術的發展。' },
      { en: 'Fauvism',
        def: 'Early twentieth-century French movement known for bold, non-naturalistic color.',
        zh: '野獸派',
        zhDef: '二十世紀初的法國藝術運動，以大膽、非寫實的用色著稱。' },
      { en: 'Cubism (1907–1918, Picasso, Braque)',
        def: 'Rejected single-point perspective in favor of multiple simultaneous viewpoints; moved toward geometric/rational abstraction, collage, and an emphasis on materials.',
        zh: '立體主義（1907–1918，畢卡索、布拉克）',
        zhDef: '捨棄單一透視法，改採多重、同時並存的觀看角度；朝向幾何／理性的抽象化、拼貼，並強調材質本身。' },
      { en: 'Expressionism (Germany, from 1910)',
        def: 'Emphasized figuration, directness, and intense color/line to convey psychological and social pressure; explicitly opposed abstraction and was later suppressed by the Nazi regime.',
        zh: '表現主義 （德國，始於1910年）',
        zhDef: '強調具象、直接性與強烈的色彩／線條，以傳達心理與社會的壓力；明確反對抽象化，後來遭納粹政權打壓。' },
      { en: 'Constructivism (Russia, Vladimir Tatlin)',
        def: 'An anti-"art for art\'s sake" movement using industrial materials and found objects, aiming to serve the construction of a new society.',
        zh: '構成主義 （俄國，塔特林）',
        zhDef: '一種反對「為藝術而藝術」的運動，運用工業材料與現成物，旨在為建構新社會服務。' },
      { en: 'De Stijl (the Netherlands, Piet Mondrian)',
        def: 'Also called Neoplasticism; reduced form to geometric shapes and primary colors plus black and white.',
        zh: '風格派（荷蘭，蒙德里安）',
        zhDef: '又稱新造形主義；將形式化約為幾何形狀，以及原色加上黑白。' },
      { en: 'Suprematism (Russia, Kazimir Malevich)',
        def: 'Founded c.1913; emphasized basic geometric forms and a limited palette, aiming for a "supremacy of pure feeling" independent of any depicted object.',
        zh: '至上主義（俄國，馬列維奇）',
        zhDef: '約創立於1913年；強調基本幾何形式與有限色彩，追求一種不依附任何描繪對象、獨立存在的「純粹感受的至上性」。' },
      { en: 'Futurism (Italy, Umberto Boccioni)',
        def: 'Glorified speed, technology, and even violence; celebrated the machine age and modern warfare.',
        zh: '未來主義（義大利，薄丘尼）',
        zhDef: '歌頌速度、科技乃至暴力；讚揚機械時代與現代戰爭。' },
      { en: 'Bauhaus',
        def: 'German art and design school (with faculty including Kandinsky and Paul Klee) that shaped later thinking on the relationship between art, architecture, design, and art education.',
        zh: '包浩斯',
        zhDef: '德國藝術與設計學校（師資包括康丁斯基與保羅·克利），形塑了後世對藝術、建築、設計與藝術教育之間關係的思考。' },
      { en: 'Armory Show (1913)',
        def: 'The exhibition that introduced European modern art (Impressionism, Cubism, Futurism) to American audiences.',
        zh: '軍械庫展覽（1913年）',
        zhDef: '將歐洲現代藝術（印象派、立體主義、未來主義）引介給美國觀眾的展覽。' },
    ]
  },
  {
    n: 2, dir: 'week03',
    title: 'Expression and the Inner Self',
    zh: '表現與內在自我：藝術如何呈現情感與潛意識？',
    terms: [
      { en: 'Dada',
        def: 'An anti-art movement (started 1916, Zurich) that rejected logic, tradition, and conventional beauty in response to the trauma of WWI.',
        zh: '達達',
        zhDef: '一場反藝術運動（1916年始於蘇黎世），為回應第一次世界大戰的創傷，拒絕邏輯、傳統與傳統美感。' },
      { en: 'Anti-art',
        def: 'Art that questions or rejects the idea of "art" itself.',
        zh: '反藝術',
        zhDef: '質疑或拒絕「藝術」這個概念本身的藝術。' },
      { en: 'Readymade',
        def: 'An everyday object chosen by an artist and presented as a work of art, as in Marcel Duchamp\'s Fountain (1917).',
        zh: '現成物',
        zhDef: '藝術家選取日常物件並將其呈現為藝術作品，如杜象的《噴泉》（1917年）。' },
      { en: 'Manifesto',
        def: 'A public written statement of an artist group\'s beliefs and goals (e.g., Tzara\'s Dada Manifesto, Breton\'s Surrealist Manifesto).',
        zh: '宣言',
        zhDef: '藝術團體公開發表、闡述其信念與目標的書面聲明（例如查拉的《達達宣言》、布荷東的《超現實主義宣言》）。' },
      { en: 'Automatism',
        def: 'Creating art without conscious control, letting the unconscious mind guide the hand.',
        zh: '自動主義',
        zhDef: '在無意識控制下進行創作，讓潛意識引導手部動作。' },
      { en: 'The Unconscious',
        def: 'The part of the mind we are not aware of, but that affects thought and behavior; central to Freud\'s theory and to Surrealism.',
        zh: '潛意識',
        zhDef: '心智中我們未能察覺、卻會影響思想與行為的部分；是佛洛伊德理論與超現實主義的核心概念。' },
      { en: 'Surrealism',
        def: 'An art movement founded by André Breton in 1924, based on dreams and the unconscious mind.',
        zh: '超現實主義',
        zhDef: '由布荷東於1924年創立的藝術運動，以夢境與潛意識為基礎。' },
      { en: 'Installation art',
        def: 'Art designed to transform how a viewer experiences a particular space, often three-dimensional and site-specific, immersing the viewer within the work rather than presenting it as a discrete object to view from a distance.',
        zh: '裝置藝術',
        zhDef: '旨在改變觀者對特定空間之體驗方式的藝術，通常具有三維性且因地制宜，讓觀者沉浸於作品之中，而非從遠處觀看某個獨立的物件。' },
      { en: 'Site-specific',
        def: 'Describes a work created for, and dependent on, a particular location; moving it elsewhere would fundamentally change or destroy its meaning.',
        zh: '因地制宜／場域特定',
        zhDef: '指為特定地點創作、且依附於該地點的作品；若將其移至他處，作品的意義將被根本改變或破壞。' },
      { en: 'Documentary photography',
        def: 'Photography intended to record real events, places, or social conditions with a claim to truthfulness; in the context of Surrealism and wartime art, often contrasted with staged or manipulated imagery.',
        zh: '紀實攝影',
        zhDef: '旨在如實記錄真實事件、地點或社會情況的攝影，帶有真實性的訴求；在超現實主義與戰時藝術的脈絡中，常與擺拍或經過操弄的影像相對照。' },
      { en: 'Collage',
        def: 'A technique of composing an artwork by pasting together fragments of paper, fabric, photographs, or other found materials onto a surface; pioneered by Cubism and central to Dada and Surrealist practice.',
        zh: '拼貼',
        zhDef: '將紙張、布料、照片或其他現成材料的碎片黏貼組合於平面上以構成作品的技法；由立體主義開創，並成為達達與超現實主義創作的核心手法。' },
      { en: 'Frottage',
        def: 'A technique invented by Max Ernst in which paper is placed over a textured surface (such as wood grain) and rubbed with pencil or crayon to bring out an image from the resulting pattern, echoing automatism\'s reliance on chance.',
        zh: '拓印法',
        zhDef: '恩斯特發明的一種技法，將紙張覆蓋於具紋理的表面（如木紋）上，以鉛筆或蠟筆摩擦，使圖像從產生的紋路中浮現，呼應自動主義對機遇的依賴。' },
      { en: 'Grattage',
        def: 'A related technique developed by Max Ernst in which paint is applied to a canvas placed over a textured object and then scraped away, allowing the underlying texture to shape the resulting image.',
        zh: '刮擦法',
        zhDef: '恩斯特發展出的相關技法，將顏料塗於覆蓋在具紋理物體上的畫布上，再刮除顏料，讓底層的紋理形塑出最終的圖像。' },
      { en: 'Paranoiac-critical method',
        def: 'Salvador Dalí\'s technique for accessing irrational, dreamlike imagery by deliberately inducing a paranoid state of mind, then rendering the resulting hallucinatory associations with painstaking, realistic precision.',
        zh: '偏執狂批判法',
        zhDef: '達利用以取用非理性、夢境般意象的技法，透過刻意誘發一種偏執狀態，再以極其精細寫實的手法描繪由此產生的幻覺式聯想。' },
      { en: 'Biomorphic',
        def: 'Abstract shapes that suggest living or organic forms.',
        zh: '生物形態',
        zhDef: '暗示有機生命形體的抽象形狀。' },
      { en: 'Veristic / Illusionistic',
        def: 'Painted with realistic detail, even though the subject itself is impossible or dreamlike.',
        zh: '寫實／幻覺式',
        zhDef: '以寫實細膩的手法描繪，儘管所畫的主題本身不可能存在或帶有夢境般的性質。' },
      { en: 'École de Paris (School of Paris)',
        def: 'Artists of many nationalities working in Paris, 1919–1950s, modern in intent but still figurative.',
        zh: '巴黎畫派',
        zhDef: '1919至1950年代間，在巴黎工作、來自多國籍的藝術家群體，創作意圖上屬於現代，但仍維持具象風格。' },
      { en: 'American Scene painting',
        def: '1930s American art movement (Regionalism and Social Realism) focused on distinctly "American" subjects.',
        zh: '美國景象畫派',
        zhDef: '1930年代美國藝術運動（包含地方主義與社會寫實主義），聚焦於具鮮明「美國性」的主題。' },
      { en: 'Mural',
        def: 'A large painting made directly on a wall, often for a public building; central to the Mexican Mural Movement.',
        zh: '壁畫',
        zhDef: '直接繪製於牆面的大型繪畫，常見於公共建築；是墨西哥壁畫運動的核心。' },
      { en: 'Interwar period',
        def: 'The years between World War I and World War II (1918–1939).',
        zh: '戰間期',
        zhDef: '第一次世界大戰與第二次世界大戰之間的年代（1918–1939年）。' },
    ]
  },
  {
    n: 3, dir: 'week04',
    title: 'From Representation to Expression',
    zh: '從再現到表現：繪畫如何脫離現實？',
    terms: [
      { en: 'Figurative / Representational Art',
        def: 'Art that depicts recognizable subjects drawn from external, observable reality.',
        zh: '具象／再現藝術',
        zhDef: '描繪取自外在、可觀察現實中可辨識主體的藝術。' },
      { en: 'Abstraction',
        def: 'Art that departs from the recognizable representation of objects, emphasizing color, form, and process instead.',
        zh: '抽象',
        zhDef: '脫離對物件可辨識再現的藝術，轉而強調色彩、形式與過程本身。' },
      { en: 'Abstract Expressionism',
        def: 'Term first applied by critic Robert Coates in 1946 to contemporary New York painting; not one unified style but a historical period (c.1943–1960s), a shared creative ideal, and an umbrella covering several distinct movements.',
        zh: '抽象表現主義',
        zhDef: '由評論家羅伯特·科茨於1946年首度用來指稱當時的紐約繪畫；並非單一統合的風格，而是一個歷史時期（約1943–1960年代）、一種共同的創作理念，同時涵蓋數個不同的運動。' },
      { en: 'Automatism',
        def: 'A Surrealist technique of suspending conscious, rational control during creation so that the unconscious guides the artist\'s hand; adapted by Abstract Expressionists such as Pollock.',
        zh: '自動主義',
        zhDef: '超現實主義的技法，創作時暫停有意識的理性控制，讓潛意識引導藝術家的手部動作；後為帕洛克等抽象表現主義藝術家所採用。' },
      { en: 'All-over Technique',
        def: 'Clement Greenberg\'s term for a composition — especially Pollock\'s — in which paint, line, and color spread evenly across the entire canvas with no single focal point.',
        zh: '滿版技法',
        zhDef: '格林伯格用來形容一種構圖方式的術語──尤指帕洛克的作品──顏料、線條與色彩均勻地擴散至整個畫布，沒有單一焦點。' },
      { en: 'Art Brut ("raw art")',
        def: 'Term coined by Jean Dubuffet in 1945 for art made outside formal training and social convention, exemplified by the work of psychiatric patients and other self-taught outsiders.',
        zh: '原生藝術（粗獷藝術）',
        zhDef: '由杜布菲於1945年提出的術語，指未經正規訓練、脫離社會慣例所創作的藝術，以精神病患及其他自學藝術家的作品為代表。' },
      { en: 'Émigré / exile artist',
        def: 'An artist displaced from their home country by war or persecution; many Surrealists fled Europe for New York during WWII, bringing automatism with them.',
        zh: '流亡／移居藝術家',
        zhDef: '因戰爭或迫害而被迫離開祖國的藝術家；許多超現實主義者在二戰期間逃離歐洲前往紐約，將自動主義一併帶去。' },
      { en: 'Art of This Century',
        def: 'Peggy Guggenheim\'s New York gallery (opened 1942), where exiled European Surrealists met and directly influenced a new generation of American painters, including Jackson Pollock.',
        zh: '本世紀藝術畫廊',
        zhDef: '佩姬·古根漢於1942年在紐約開設的畫廊，流亡的歐洲超現實主義者在此聚集，並直接影響了包括帕洛克在內的新一代美國畫家。' },
      { en: 'Action Painting',
        def: 'Term coined by critic Harold Rosenberg in 1952 to describe the work of Pollock, de Kooning, and others: formless, improvisational, dynamic, and valuing the artist\'s physical action as much as the finished image.',
        zh: '行動繪畫',
        zhDef: '評論家哈洛德·羅森伯格於1952年提出的術語，用以描述帕洛克、德庫寧等人的作品：無固定形式、即興、充滿動勢，重視藝術家的身體行動不亞於重視完成後的畫面。' },
      { en: 'The New York School',
        def: 'Collective name for the Abstract Expressionists, reflecting New York\'s emergence as the new center of the art world after World War II, displacing prewar Paris.',
        zh: '紐約畫派',
        zhDef: '抽象表現主義者的集體稱號，反映出紐約在二戰後取代戰前的巴黎，成為藝術世界的新中心。' },
      { en: 'Color-field Painting',
        def: 'Large, flat expanses of color meant to convey feeling directly, associated with Barnett Newman and Mark Rothko.',
        zh: '色域繪畫',
        zhDef: '以大面積、平塗的色塊直接傳達情感，與紐曼、羅斯科相關。' },
      { en: 'Soak-Stain',
        def: 'Helen Frankenthaler\'s technique of pouring heavily thinned paint directly onto unprimed canvas so that it soaks into the fabric rather than sitting on the surface, producing soft, luminous fields of color; foundational to Post-Painterly Abstraction.',
        zh: '浸染法',
        zhDef: '法蘭肯薩勒的技法，將高度稀釋的顏料直接倒在未經打底的畫布上，使顏料滲入布料纖維而非停留於表面，產生柔和、透亮的色域；是後繪畫性抽象的基礎技法。' },
      { en: 'Post-Painterly Abstraction',
        def: 'Term coined by critic Clement Greenberg in 1964 to describe a "second generation" of abstraction — exemplified by Helen Frankenthaler — marked by soft-edged, free-flowing washes of color.',
        zh: '後繪畫性抽象',
        zhDef: '評論家格林伯格於1964年提出的術語，用以描述抽象藝術的「第二代」──以法蘭肯薩勒為代表──特色為柔邊、流動自如的色彩渲染。' },
      { en: 'Hard-Edge Painting',
        def: 'A mode of abstraction, associated with Ellsworth Kelly, that excludes chance and gesture in favor of crisp, deliberate shapes and flat color areas.',
        zh: '硬邊繪畫',
        zhDef: '與凱利相關的一種抽象模式，排除偶然性與筆觸痕跡，改以俐落、明確的形狀與平塗色域為主。' },
      { en: 'Art Informel',
        def: 'A European (largely Parisian) movement emerging around 1945 and named by critic Michel Tapié in his 1952 exhibition Un Art Autre ("Another Art"); lyrical, improvisational abstraction expressing the unconscious rather than representing any concrete object — what critics called "Psychic Improvisation."',
        zh: '非形式藝術',
        zhDef: '約於1945年興起於歐洲（主要在巴黎）的運動，由評論家塔皮耶於1952年的展覽《另一種藝術》（Un Art Autre）命名；一種抒情、即興的抽象藝術，表現潛意識而非再現任何具體對象──評論家稱之為「心靈即興」。' },
      { en: 'Matter Painting',
        def: 'A postwar European tendency, closely related to Art Informel, in which thick, raw materials (sand, tar, plaster, torn fabric) are worked directly into the painted surface, emphasizing texture and physical substance over illusionistic depiction.',
        zh: '物質繪畫',
        zhDef: '戰後歐洲與非形式藝術密切相關的一種傾向，將厚重、粗獷的材料（沙、瀝青、灰泥、破布）直接融入畫面之中，強調質地與物質性本身，而非幻覺式的描繪。' },
    ]
  },
  {
    n: 4, dir: 'week05',
    title: 'The Boundary Between Art and Everyday Life',
    zh: '藝術與日常生活的界線：任何東西都能是藝術嗎？',
    terms: [
      { en: 'Pop Art',
        def: 'Term coined in 1958 by British critic Lawrence Alloway in "The Arts and the Mass Media," referring to art that engages directly with popular and mass culture.',
        zh: '普普藝術',
        zhDef: '英國評論家羅倫斯·阿洛威於1958年在《藝術與大眾媒體》一文中提出的術語，指直接與大眾流行文化互動的藝術。' },
      { en: 'Mass Culture / Popular Culture',
        def: 'Commercial imagery from advertising, comics, television, and consumer goods that Pop artists drew upon and recontextualized as art.',
        zh: '大眾文化／流行文化',
        zhDef: '來自廣告、漫畫、電視與消費商品的商業影像，普普藝術家將其挪用並重新脈絡化為藝術。' },
      { en: 'The Artworld',
        def: 'Arthur Danto\'s 1964 theory that an object becomes art through an atmosphere of theory, a knowledge of art history, and an institutional context — not through its appearance alone.',
        zh: '藝術世界',
        zhDef: '丹托於1964年提出的理論，認為一件物品之所以成為藝術，是透過理論的氛圍、藝術史知識與體制脈絡──而非僅憑外觀。' },
      { en: 'Silkscreen Printing',
        def: 'A mechanical printmaking process central to Warhol\'s aesthetic of mass production, deliberately effacing the individual hand of the artist.',
        zh: '絹印',
        zhDef: '一種機械化的印刷製版過程，是沃荷式大量生產美學的核心，刻意抹去藝術家個人手感的痕跡。' },
      { en: 'Ben-Day Dots',
        def: 'A mechanical dot-printing technique from mass-produced comics that Lichtenstein enlarged and reproduced by hand, exposing the mechanics of image reproduction.',
        zh: '班戴點',
        zhDef: '源自大量印製漫畫的一種機械式圓點印刷技法，李奇登斯坦將其放大並以手工重製，藉此揭露影像複製的機制。' },
      { en: 'Found Object (objet trouvé)',
        def: 'An everyday or discarded item incorporated directly into an artwork; central to both Assemblage and Neo-Dada, and traceable to Duchamp\'s readymades.',
        zh: '現成物',
        zhDef: '直接被納入作品中的日常或廢棄物件；是集合藝術與新達達的核心，其源頭可追溯至杜象的現成物。' },
      { en: 'Avant-Garde',
        def: 'Broadly, artists or works that are experimental and ahead of their time, challenging existing conventions; in art-historical theory (e.g., Peter Bürger), the term refers specifically to early-twentieth-century movements (Dada, Surrealism, Constructivism) that sought to reintegrate art into the practice of everyday life.',
        zh: '前衛',
        zhDef: '廣義而言，指實驗性、走在時代之前、挑戰既有慣例的藝術家或作品；在藝術史理論中（如彼得·比格），此詞特指二十世紀初期試圖將藝術重新整合進日常生活實踐的運動（達達、超現實主義、構成主義）。' },
      { en: 'Kitsch',
        def: 'Clement Greenberg\'s term (from his 1939 essay "Avant-Garde and Kitsch") for mass-produced, sentimental, formulaic imagery designed for easy consumption; Pop Art deliberately drew on kitsch imagery, blurring the line Greenberg had drawn between high art and low culture.',
        zh: '媚俗',
        zhDef: '格林伯格的用語（出自其1939年文章〈前衛與媚俗〉），指大量生產、感傷、公式化、便於輕鬆消費的影像；普普藝術刻意援引媚俗影像，模糊了格林伯格所劃分的高級藝術與低俗文化之間的界線。' },
      { en: 'Appropriation',
        def: 'The strategy of taking existing images, objects, or styles from art history, advertising, or mass media and re-presenting them, often with little or no alteration, so that the act of selection itself becomes the artistic gesture.',
        zh: '挪用',
        zhDef: '擷取藝術史、廣告或大眾媒體中既有的影像、物件或風格，加以重新呈現的策略，往往幾乎不加改動，使「選取」這個行為本身成為藝術姿態。' },
      { en: 'Institutional Theory',
        def: 'A theory of art, associated with George Dickie and Arthur Danto, holding that an object becomes an artwork not through its intrinsic properties but through its status being conferred by the institutional context of the artworld (galleries, critics, museums, art history).',
        zh: '體制理論',
        zhDef: '與喬治·迪基及丹托相關的藝術理論，主張一件物品之所以成為藝術作品，並非取決於其內在特質，而是由藝術世界的體制脈絡（畫廊、評論家、美術館、藝術史）所賦予其地位。' },
      { en: 'Combine',
        def: 'Robert Rauschenberg\'s term for his own hybrid works that fuse painting and sculpture, incorporating found objects (a stuffed goat, a quilt, a tire) directly into the picture plane; Monogram (1955–59) is the best-known example.',
        zh: '組合作品',
        zhDef: '羅森伯格用來指稱自己融合繪畫與雕塑的混合式作品，將現成物（填充山羊、被子、輪胎）直接納入畫面之中；《字母組合》（1955–59年）是最著名的範例。' },
      { en: 'Assemblage',
        def: 'A technique, not a style, of constructing art from found objects, everyday materials, and discarded items; traced back to Picasso and Braque\'s 1912 "Guitar" and named as a movement by the 1961 exhibition The Art of Assemblage.',
        zh: '集合藝術',
        zhDef: '一種技法而非風格，以現成物、日常材料與廢棄物構築藝術；可追溯至畢卡索與布拉克1912年的《吉他》，並由1961年《集合藝術》（The Art of Assemblage）展覽命名為一項運動。' },
      { en: 'Neo-Dada',
        def: 'Term first used in Artnews in January 1958 to describe the work of Rauschenberg and Johns; revives Dada\'s critical spirit toward art while still constructing new aesthetic positions, rather than simply negating them.',
        zh: '新達達',
        zhDef: '1958年1月《藝術新聞》（Artnews）首度用來描述羅森伯格與瓊斯作品的術語；延續了達達對藝術的批判精神，但同時仍在建構新的美學立場，而非僅僅是否定。' },
      { en: 'Soft Sculpture',
        def: 'Sculpture made from pliable materials (canvas, vinyl, latex) that sag and deform under gravity; pioneered by Claes Oldenburg.',
        zh: '軟雕塑',
        zhDef: '以可塑材料（帆布、乙烯基、乳膠）製成、會因重力而下垂變形的雕塑；由歐登伯格開創。' },
    ]
  },
  {
    n: 5, dir: 'week06',
    title: 'Art as Action / Event',
    zh: '藝術作為行動／事件：新現實主義、偶發藝術與福魯克薩斯',
    terms: [
      { en: 'Action–Performance',
        def: 'Klein\'s and Restany\'s term for the live act of painting itself, understood as the true work, with the resulting canvas as only its residual trace.',
        zh: '行動—表演',
        zhDef: '克萊因與雷斯塔尼用來指稱繪畫這個現場行動本身即為真正作品的術語，而最終留下的畫布僅是其殘留的痕跡。' },
      { en: 'The Void / Immateriality',
        def: 'Klein\'s pursuit of an "empty" and "immaterial" art, exemplified by the 1958 exhibition The Void, which presented visitors with a bare gallery.',
        zh: '虛空／非物質性',
        zhDef: '克萊因對「空無」與「非物質」藝術的追求，以1958年《虛空》展覽為代表，該展呈現給觀眾的是一個空蕩的展覽空間。' },
      { en: 'Chance / Indeterminacy',
        def: 'John Cage\'s principle that composition should give up the composer\'s subjective control and allow structure to emerge through chance procedures and everyday sound.',
        zh: '機遇／不確定性',
        zhDef: '約翰·凱吉的原則，主張創作應放棄作曲家的主觀控制，讓結構透過機遇程序與日常聲音自然浮現。' },
      { en: 'Accumulation',
        def: 'A technique of gathering large quantities of a single type of everyday object and presenting them together as a mass, associated with Nouveau Réaliste Arman, who filled boxes and display cases with multiples of discarded objects.',
        zh: '堆積',
        zhDef: '一種收集大量同類日常物件、並將其整體堆疊呈現的技法，與新現實主義藝術家阿爾曼相關，他將大量廢棄物件填入箱子與展示櫃中。' },
      { en: 'Kinetic Sculpture',
        def: 'Sculpture that incorporates real, physical movement (motorized, wind-driven, or manually activated) as part of the work itself, rather than movement being merely implied; Jean Tinguely\'s self-destroying machines are a key example.',
        zh: '動態雕塑',
        zhDef: '將真實、物理性的運動（透過馬達、風力或人力啟動）納入作品本身的雕塑，而非僅僅暗示運動感；丁格利的自毀機械是重要範例。' },
      { en: 'Anthropométrie',
        def: 'Yves Klein\'s technique and resulting body of work in which nude models, covered in his International Klein Blue paint, pressed and dragged their bodies directly across canvas, using the human body itself as the "living brush."',
        zh: '人體測量',
        zhDef: '克萊因的技法及由此產生的系列作品，讓塗滿其國際克萊因藍顏料的裸體模特兒，直接以身體壓印、拖曳過畫布，將人體本身當作「活的畫筆」。' },
      { en: 'Happening',
        def: 'A term coined by Allan Kaprow for an event staged across more than one time and place, co-created by performers and observers rather than presented to a passive audience.',
        zh: '偶發藝術',
        zhDef: '卡布羅所提出的術語，指涉及多個時間與地點、由表演者與觀眾共同創造，而非提供給被動觀眾觀看的事件。' },
      { en: 'Expanded Concept of Art (Erweiterter Kunstbegriff)',
        def: 'Joseph Beuys\'s idea that artistic material and action extend to any object or act drawn from and shaping everyday life.',
        zh: '擴展的藝術概念',
        zhDef: '波依斯的理念，主張藝術的材料與行動可延伸至任何取自日常生活、並反過來形塑日常生活的物件或行為。' },
      { en: 'Nouveau Réalisme',
        def: 'A movement formed around French critic Pierre Restany and artists including Yves Klein, formulated as a counterpart to American Neo-Dada; it called for art to record "sociological reality" directly, without the rhetoric of Expressionism or Social Realism.',
        zh: '新現實主義',
        zhDef: '以法國評論家雷斯塔尼及包括克萊因在內的藝術家群體所組成的運動，作為對應美國新達達的對照；主張藝術應直接記錄「社會學的現實」，而不採用表現主義或社會寫實主義的修辭方式。' },
      { en: 'Fluxus',
        def: 'A loose international network of artists active from the early 1960s (formally launched at Maciunas\'s 1962 Wiesbaden festival), producing publications, manifestos, and performances; its name, from the Latin for "flow," reflects its refusal of a fixed definition or style.',
        zh: '福魯克薩斯',
        zhDef: '自1960年代初活躍至今的鬆散國際藝術網絡（於馬希烏納斯1962年在威斯巴登舉辦的藝術節上正式成立），發表出版品、宣言與表演；其名稱源自拉丁文「流動」之意，反映其拒絕固定定義或風格的立場。' },
    ]
  },
  {
    n: 6, dir: 'week07',
    title: 'From Object to Concept',
    zh: '從物件到觀念：藝術還需要以實體存在嗎？',
    terms: [
      { en: 'Expanded Concept of Art (Erweiterter Kunstbegriff)',
        def: 'Joseph Beuys\'s theory that art\'s materials and means are unlimited — thought, speech, and social action are as artistic as paint or stone.',
        zh: '擴展的藝術概念',
        zhDef: '波依斯的理論，主張藝術的材料與手段是無限的──思想、言語與社會行動與顏料或石材同樣具有藝術性。' },
      { en: 'Social Sculpture',
        def: 'Beuys\'s idea that society itself can be "sculpted" through collective, participatory action; distilled in his statement "Everyone is an artist."',
        zh: '社會雕塑',
        zhDef: '波依斯的理念，主張社會本身可透過集體、參與式的行動被「雕塑」；其名言「人人都是藝術家」正是此理念的濃縮。' },
      { en: 'Specific Objects',
        def: 'Donald Judd\'s term (from his 1965 essay of the same name) for work that is "neither painting nor sculpture," existing instead as a literal three-dimensional object in real space.',
        zh: '特定物',
        zhDef: '唐納德·賈德的術語（出自其1965年同名文章），指稱「既非繪畫亦非雕塑」的作品，而是以真實空間中字面意義上的三維物件形式存在。' },
      { en: 'De-aestheticization',
        def: 'The drive, especially strong in Minimalism, to strip away decorative or expressive aesthetic qualities so the work is encountered as a plain fact or object rather than a display of skill or sentiment.',
        zh: '去美學化',
        zhDef: '在極簡主義中尤為強烈的一種傾向，剝除裝飾性或表現性的美學特質，使作品被視為單純的事實或物件，而非技巧或情感的展示。' },
      { en: 'Reduction',
        def: 'Minimalism\'s continuation of Clement Greenberg\'s formalist logic, pursuing an artwork\'s irreducible essence toward self-sufficient purity and autonomy.',
        zh: '還原／化約',
        zhDef: '極簡主義對格林伯格形式主義邏輯的延續，追求作品不可再化約的本質，朝向自足的純粹性與自律性。' },
      { en: 'Seriality',
        def: 'The use of mathematical or logical, repeated sequences in Minimalist production, which anticipated the systematic, rule-based methods later used in Conceptual and Process art.',
        zh: '序列性',
        zhDef: '極簡主義創作中運用數學或邏輯性的重複序列，預示了後來觀念藝術與過程藝術所採用的系統化、規則導向的方法。' },
      { en: 'Concept Art',
        def: 'Term first used in 1961 by Fluxus-affiliated artist and writer Henry Flynt, who wrote that "the material of such art is concepts, as sound is the material of music."',
        zh: '觀念藝術',
        zhDef: '1961年由福魯克薩斯相關藝術家暨作家亨利·弗林特首度使用的術語，他寫道：「此類藝術的材料是概念，正如聲音是音樂的材料。」' },
      { en: 'The Idea Becomes a Machine',
        def: 'Sol LeWitt\'s phrase from "Paragraphs on Conceptual Art" (Artforum, 1967–68): once an artist\'s idea and decisions are fixed in advance, execution is a formality — even imprecise execution is acceptable, because the idea itself is what makes the art.',
        zh: '觀念變成機器',
        zhDef: '索爾·勒維特於〈關於觀念藝術的段落〉（《藝術論壇》，1967–68年）一文中的說法：一旦藝術家的觀念與決定事先確立，執行便僅是形式上的手續──即使執行不夠精確也無妨，因為使藝術成立的是觀念本身。' },
      { en: 'Art as Proposition',
        def: 'Joseph Kosuth\'s claim, from "Art After Philosophy" (1969), that an artwork represents the artist\'s intention and is simultaneously art and a definition of art — so the proposition precedes the physical object and its logical structure.',
        zh: '藝術即命題',
        zhDef: '約瑟夫·科史士在〈藝術之後的哲學〉（1969年）一文中的主張：藝術作品呈現藝術家的意圖，同時既是藝術、也是藝術自身的定義──因此命題先於物理物件及其邏輯結構而存在。' },
      { en: 'Industrial fabrication',
        def: 'The practice, central to Minimalism (especially Donald Judd), of having works manufactured off-site by industrial workshops according to the artist\'s specifications, removing the artist\'s hand from the physical making of the object.',
        zh: '工業製造',
        zhDef: '極簡主義（尤以唐納德·賈德為代表）的核心作法，依藝術家的規格，委由場外的工業工廠製作作品，將藝術家的手完全排除於物件的實際製作過程之外。' },
      { en: 'Tautology',
        def: 'In Conceptual Art, especially Joseph Kosuth\'s usage, the idea that an artwork can be a self-referential statement that is true simply by definition, defining art in terms of art itself rather than referring to anything outside it.',
        zh: '套套邏輯',
        zhDef: '在觀念藝術中，尤其是科史士的用法，指藝術作品可以是一種自我指涉的陳述，僅憑定義本身即為真，以藝術自身來定義藝術，而不指涉任何外在之物。' },
      { en: 'Ontology',
        def: 'The branch of philosophy concerned with the nature of being and existence; in Conceptual Art, artists such as Kosuth used ontological questions to ask what kind of thing an artwork actually is.',
        zh: '存有論',
        zhDef: '探討存在本質的哲學分支；在觀念藝術中，科史士等藝術家運用存有論式的提問，探究藝術作品究竟是什麼樣的存在。' },
      { en: 'Epistemology',
        def: 'The branch of philosophy concerned with the nature and limits of knowledge; Conceptual artists drew on epistemology to question how, and whether, an artwork can convey or constitute knowledge.',
        zh: '知識論',
        zhDef: '探討知識之本質與限度的哲學分支；觀念藝術家借用知識論，質問藝術作品究竟能否、以及如何傳達或構成知識。' },
      { en: 'Declaration of intent',
        def: 'A written statement by the artist specifying a work\'s concept and instructions for its execution; in Conceptual and Minimal Art (e.g., Sol LeWitt\'s wall drawing instructions), this written statement can itself constitute the artwork, independent of its physical realization.',
        zh: '意圖聲明',
        zhDef: '藝術家撰寫、說明作品概念及執行指示的書面聲明；在觀念藝術與極簡主義中（例如索爾·勒維特的壁畫指示），這份書面聲明本身即可構成作品，獨立於其物理性的實現之外。' },
      { en: 'Dematerialization',
        def: 'Lucy Lippard and John Chandler\'s term (1968) for Conceptual Art\'s tendency to shift emphasis away from the physical, permanent art object and toward idea, language, and documentation.',
        zh: '去物質化',
        zhDef: '露西·利帕德與約翰·錢德勒於1968年提出的術語，指觀念藝術將重心從物理性、恆久的藝術物件，轉移至觀念、語言與紀錄的傾向。' },
      { en: 'Institutional Critique',
        def: 'An extension of Conceptual Art, developed from the late 1960s onward, that turns the artwork\'s inquiry onto the museum, gallery, or art market itself as subject matter; exemplified by Hans Haacke.',
        zh: '體制批判',
        zhDef: '觀念藝術的延伸，自1960年代晚期發展而來，將作品的探問轉向美術館、畫廊或藝術市場本身作為探討對象；以漢斯·哈克為代表。' },
      { en: 'Minimalism',
        def: 'Emerged in the mid-1960s in tension with Fluxus\'s embrace of change and event; used the fewest possible materials, colors, and forms to emphasize an object\'s plain, unchanging presence, prompting viewers to ask whether art objects need to be transformed from ordinary ones at all.',
        zh: '極簡主義',
        zhDef: '於1960年代中期興起，與福魯克薩斯擁抱變化與事件性的傾向形成張力；運用盡可能精簡的材料、色彩與形式，強調物件單純、恆常不變的存在，促使觀者思考藝術物件是否真的需要與一般物件有所區隔。' },
      { en: 'Conceptual Art',
        def: 'A movement that developed from the mid-1960s, growing out of Minimalism\'s emphasis on idea over form (Judd, LeWitt) and Duchamp\'s readymade tradition; per the 1996 Dictionary of Art, it privileges the work\'s concept over its physical object and realistic representation, with artists especially concerned about the political or environmental context their work carries.',
        zh: '觀念藝術',
        zhDef: '自1960年代中期發展而來的運動，源自極簡主義對觀念重於形式的強調（賈德、勒維特）以及杜象現成物的傳統；根據1996年版《藝術辭典》，此運動重視作品的概念本身，勝過其物理物件與寫實再現，藝術家尤其關注作品所承載的政治或環境脈絡。' },
    ]
  },
  {
    n: 7, dir: 'week08',
    title: 'Anti-Form',
    zh: '反形式：當過程取代了完成的作品',
    terms: [
      { en: 'Anti-Form',
        def: 'Robert Morris\'s term from his 1968 Artforum essay "Anti Form," arguing that a material\'s own physical properties and the process acting on it (dropping, hanging, pouring) should determine a work\'s shape, rather than a preconceived, fixed configuration — a direct break from Minimalism\'s rigid geometry.',
        zh: '反形式',
        zhDef: '羅伯特·莫里斯於1968年《藝術論壇》文章〈反形式〉中提出的術語，主張應由材料本身的物理特性及作用於其上的過程（垂落、懸掛、傾倒）來決定作品的形狀，而非事先預定、固定的構造──直接背離極簡主義僵固的幾何形式。' },
      { en: 'Process / Time',
        def: 'In Process Art, "process" refers to the process that constitutes the artwork itself: the making matters more than the finished result, and time and space become active materials rather than a neutral setting for display.',
        zh: '過程／時間',
        zhDef: '在過程藝術中，「過程」指構成作品本身的過程：製作的行為比最終結果更重要，時間與空間成為主動的材料，而非展示時中立的背景。' },
      { en: 'Op Art (Optical Art)',
        def: 'Term first applied by Time magazine in 1964; popularized internationally by MoMA\'s 1965 exhibition The Responsive Eye, curated by William C. Seitz, which drew over 180,000 visitors.',
        zh: '歐普藝術',
        zhDef: '1964年由《時代》雜誌首度使用的術語；經由紐約現代美術館1965年由威廉·C·賽茲策劃的《回應之眼》展覽在國際間普及，該展吸引超過18萬名觀眾。' },
      { en: 'Retinal Art / Perceptual Abstraction',
        def: 'Alternate names for Op Art emphasizing that the work acts on the eye\'s physiology rather than emotion or subject matter; artists treated the picture as a scientific, near-experimental problem rather than an expressive one.',
        zh: '視網膜藝術／知覺抽象',
        zhDef: '歐普藝術的另稱，強調作品作用於眼睛的生理機制，而非情感或主題內容；藝術家將畫面視為一種科學性、近乎實驗性的問題，而非表現性的問題。' },
      { en: 'Photorealism (Super-Realism)',
        def: 'Term coined in 1969 by New York dealer Louis K. Meisel; first appeared in print in 1970 in the Whitney Museum\'s catalogue for Twenty-two Realists. In 1972 Meisel formalized a five-point definition requiring a photographic source, mechanical transfer to canvas, and a finished surface indistinguishable from a photograph.',
        zh: '照相寫實主義',
        zhDef: '1969年由紐約畫商路易斯·K·梅塞爾提出的術語；1970年首度出現於惠特尼美術館《二十二位寫實主義者》展覽圖錄中。1972年梅塞爾正式提出五點定義，要求須有攝影來源、以機械方式轉印至畫布，以及與照片無法區辨的完成表面。' },
      { en: 'Process Art',
        def: 'Movement named by two landmark 1969 exhibitions — When Attitudes Become Form (Kunsthalle Bern, curated by Harald Szeemann) and Anti-Illusion: Procedures/Materials (Whitney Museum) — that treated gathering, arranging, and physically acting on unconventional materials as the artwork\'s real subject; its precursors include Jackson Pollock\'s action painting and Morris Louis\'s pouring technique (color-field painting), both prized for foregrounding the physical act of painting.',
        zh: '過程藝術',
        zhDef: '由1969年兩場具指標性的展覽命名的運動──《當態度變成形式》（伯恩美術館，哈洛德·塞曼策劃）與《反幻覺：程序／材料》（惠特尼美術館）──將收集、排列與對非傳統材料進行physical動作視為作品真正的主題；其先驅包括帕洛克的行動繪畫與莫里斯·路易斯的傾倒技法（色域繪畫），兩者皆因凸顯繪畫的physical行動而備受推崇。' },
      { en: 'Institutional Critique',
        def: 'An extension of Conceptual Art, developed from the late 1960s onward, that turns the artwork\'s inquiry onto the museum, gallery, or art market itself as subject matter; exemplified by Hans Haacke.',
        zh: '體制批判',
        zhDef: '觀念藝術的延伸，自1960年代晚期發展而來，將作品的探問轉向美術館、畫廊或藝術市場本身作為探討對象；以漢斯·哈克為代表。' },
    ]
  },
  {
    n: 8, dir: 'week09',
    title: 'Leaving the Museum',
    zh: '走出美術館：藝術進入世界',
    terms: [
      { en: 'Arte Povera',
        def: 'Term coined by Italian critic Germano Celant in 1967 to describe a loosely connected group of Italian artists who used humble, everyday, or organic materials to critique industrial consumer culture.',
        zh: '貧窮藝術',
        zhDef: '義大利評論家傑爾馬諾·切蘭特於1967年提出的術語，用以描述一群鬆散聯繫的義大利藝術家，他們運用卑微、日常或有機的材料來批判工業消費文化。' },
      { en: 'Entropy',
        def: 'Smithson\'s borrowed thermodynamic concept describing an artwork\'s inevitable, irreversible change or decay over time; central to Spiral Jetty and to Land Art\'s embrace of natural forces.',
        zh: '熵',
        zhDef: '史密森借用自熱力學的概念，描述作品隨時間必然、不可逆的變化或衰敗；是《螺旋防波堤》及大地藝術擁抱自然力量的核心概念。' },
      { en: 'Site / Nonsite',
        def: 'Smithson\'s paired terms distinguishing an outdoor "real" location (Site) from its indoor gallery representation through maps, photographs, or collected material samples (Nonsite).',
        zh: '場址／非場址',
        zhDef: '史密森成對提出的術語，區分戶外「真實」的地點（Site）與其在室內畫廊中透過地圖、照片或採集的材料樣本所呈現的再現形式（Nonsite）。' },
      { en: 'Ephemeral / Process-Based Art',
        def: 'Artworks intentionally left to change or disappear through natural forces or time rather than preserved as permanent objects; central to Richard Long and Andy Goldsworthy.',
        zh: '短暫性／過程本位藝術',
        zhDef: '刻意任其隨自然力量或時間變化、消逝，而非以永久物件形式保存的作品；是朗恩及戈兹沃西創作的核心。' },
      { en: 'Found / Poor Materials',
        def: 'Raw, humble, or discarded materials (rags, coal, twigs, lettuce, live animals) used in place of traditional art media, rejecting a hierarchy of "high art" materials; central to Arte Povera.',
        zh: '現成／貧窮材料',
        zhDef: '以粗糙、卑微或廢棄的材料（破布、煤炭、樹枝、萵苣、活體動物）取代傳統藝術媒材，拒絕「高級藝術」材料的階級之分；是貧窮藝術的核心。' },
      { en: 'Land Art (Earthworks)',
        def: 'Movement originating in the late-1960s United States in which artists created works directly in and from natural landscapes using materials such as earth, rock, and water; rejected the commercial gallery and museum as exhibition space.',
        zh: '大地藝術',
        zhDef: '興起於1960年代晚期美國的運動，藝術家直接在自然地景中、以自然地景（如泥土、岩石與水）創作；拒絕以商業畫廊與美術館作為展示空間。' },
      { en: 'Igloo',
        def: 'Mario Merz\'s recurring sculptural form, a dome-shaped structure built from varied materials (glass, metal mesh, twigs, mud), symbolizing a primal, universal form of shelter that recurs across cultures and history.',
        zh: '圓頂帳篷',
        zhDef: '馬里歐·梅爾茲反覆使用的雕塑形式，以各種材料（玻璃、金屬網、樹枝、泥土）建構出的圓頂結構，象徵跨越文化與歷史、普世共通的原初居所形式。' },
      { en: 'Fibonacci Sequence',
        def: 'A numerical sequence in which each number is the sum of the two preceding ones (1, 1, 2, 3, 5, 8...), found throughout patterns of natural growth (shells, plants); adopted by Merz as a symbol of organic, universal order underlying both nature and art.',
        zh: '費波納契數列',
        zhDef: '一組數列，其中每個數字皆為前兩個數字之和（1、1、2、3、5、8……），常見於自然生長的模式中（貝殼、植物）；梅爾茲將其採用為象徵自然與藝術背後有機、普世秩序的符號。' },
    ]
  },
  {
    n: 9, dir: 'week10',
    title: 'Expanding Media',
    zh: '擴展的媒介：錄像與身體',
    terms: [
      { en: 'Documentation',
        def: 'The photographic, video, or written record of a performance, Happening, or ephemeral artwork made after the fact; since the live event itself cannot be resold or preserved, documentation often becomes the only lasting trace of the work, raising questions about its relationship to the "original."',
        zh: '紀錄',
        zhDef: '於事後為表演、偶發藝術或短暫性作品所留下的攝影、錄像或文字紀錄；由於現場事件本身無法被轉售或保存，紀錄往往成為作品唯一留存下來的痕跡，並引發其與「原作」之間關係的提問。' },
      { en: 'Video Art',
        def: 'An art form using moving-image technology (television, video recording) as its primary medium, emerging in the 1960s alongside portable equipment such as the Sony Portapak (1965).',
        zh: '錄像藝術',
        zhDef: '以動態影像技術（電視、錄影）作為主要媒材的藝術形式，於1960年代伴隨如新力Portapak（1965年）等可攜式設備而興起。' },
      { en: 'Sony Portapak',
        def: 'The first practical, portable video recording system (released 1965), which allowed artists for the first time to record and immediately play back video outside a television studio, directly enabling the emergence of video art as an independent medium.',
        zh: '索尼可攜式錄影機',
        zhDef: '第一款實用、可攜式的錄影系統（1965年發行），讓藝術家首度能夠在電視攝影棚之外錄製並立即播放影像，直接促成了錄像藝術作為獨立媒材的興起。' },
      { en: 'Installation Art',
        def: 'Art designed to occupy and transform an entire space, often incorporating video, sound, and objects together so that the viewer physically enters and moves through the work rather than viewing it from a fixed position.',
        zh: '裝置藝術',
        zhDef: '旨在佔據並改變整個空間的藝術，經常將錄像、聲音與物件共同納入，使觀者能親身進入並穿梭於作品之中，而非從固定的位置觀看。' },
      { en: 'Closed-Circuit Video / Real-Time Feedback',
        def: 'A video installation technique in which a live camera feed is displayed to the viewer with no delay or edit, often implicating the viewer\'s own body or presence in the work; central to Paik\'s TV Buddha and Nauman\'s Corridor series.',
        zh: '閉路錄像／即時回饋',
        zhDef: '一種錄像裝置技法，將現場攝影機畫面即時、無剪接地呈現給觀者，經常使觀者自身的身體或存在被牽涉進作品之中；是白南準《電視佛陀》與諾曼《走廊》系列的核心。' },
      { en: 'Performance Art vs. Performing Arts',
        def: 'A key distinction: performing arts (theater, dance, music) typically involve rehearsal, a script, and representation on a stage; performance art typically uses the artist\'s own body, rules or instructions rather than a script, real action rather than representation, and any space rather than a stage — though the boundary between the two is not always absolute.',
        zh: '行為藝術 vs. 表演藝術',
        zhDef: '一項關鍵區別：表演藝術（戲劇、舞蹈、音樂）通常涉及排練、劇本，以及在舞台上的再現；行為藝術則通常運用藝術家自身的身體、規則或指示而非劇本、真實的行動而非再現，以及任何空間而非舞台──儘管兩者之間的界線並非總是絕對。' },
      { en: 'Presence & Duration',
        def: 'Core concepts in performance art referring to the artist\'s sustained physical presence over an extended period of time as the substance of the piece, central to Abramović\'s durational, high-risk performances such as Rhythm 0.',
        zh: '在場與持續時間',
        zhDef: '行為藝術中的核心概念，指藝術家在延長的時間內持續的physical在場，作為作品的本質；是阿布拉莫維奇《韻律0》等持續性、高風險表演的核心。' },
      { en: 'Liveness',
        def: 'The quality of being unrepeatable and dependent on real-time witnessing; distinguishes a live performance from its later photographic or video documentation.',
        zh: '現場性',
        zhDef: '一種不可重複、依賴即時見證的特質；使現場表演有別於其後的攝影或錄像紀錄。' },
      { en: 'The Documentation Loop',
        def: 'The session\'s closing framework: video art begins by asking whether the recording device can itself become the artistic medium; performance art\'s live, disappearing actions survive only through documentation, returning the discussion to that same question by the session\'s end.',
        zh: '紀錄循環',
        zhDef: '本週課程收尾的框架：錄像藝術一開始便提問，紀錄裝置本身是否能成為藝術媒材；行為藝術現場、稍縱即逝的行動，唯有透過紀錄才得以留存，到了課程尾聲，討論又回到同樣的問題。' },
      { en: 'Fluxus',
        def: 'An international, loosely organized network of artists active from the early 1960s (including Paik) emphasizing intermedia, chance, and the elevation of everyday actions to the status of art.',
        zh: '福魯克薩斯',
        zhDef: '自1960年代初活躍至今、組織鬆散的國際藝術網絡（包括白南準在內），強調跨媒介、機遇，以及將日常行動提升至藝術的地位。' },
      { en: 'Body Art',
        def: 'A branch of performance art in which the artist\'s own body is the primary medium and site of the work, as seen in Nauman, Acconci, and Abramović.',
        zh: '身體藝術',
        zhDef: '行為藝術的一支，藝術家自身的身體是作品的主要媒材與場域，可見於諾曼、阿孔奇與阿布拉莫維奇的作品。' },
      { en: 'Surveillance & Pursuit',
        def: 'Strategies of watching, tracking, or being watched — used by Nauman (Corridor), Acconci (Following Piece), and Paik (TV Buddha) to implicate viewer and subject in a shared loop of observation.',
        zh: '監視與追蹤',
        zhDef: '觀看、追蹤或被觀看的策略──由諾曼（《走廊》）、阿孔奇（《跟隨片段》）與白南準（《電視佛陀》）所運用，使觀者與主體被牽涉進共同的觀看循環之中。' },
      { en: 'Unwitting Participation / Public Intervention',
        def: 'A strategy, exemplified by Adrian Piper\'s Catalysis series, in which ordinary bystanders in public space become participants in a work without their knowledge or consent, pushing audience participation to its most extreme form.',
        zh: '不知情的參與／公共介入',
        zhDef: '一種策略，以阿德里安·派普的《催化》系列為代表，讓公共空間中的一般路人在不知情、未經同意的情況下成為作品的參與者，將觀眾參與推向最極端的形式。' },
    ]
  },
  {
    n: 10, dir: 'week11',
    title: 'Borrowed Images',
    zh: '借來的影像：原創性的終結與再現的政治',
    terms: [
      { en: 'Modernism',
        def: 'A worldview centering the rational human subject (Descartes\'s "I think, therefore I am") as the source of knowledge and truth; modernist art prized objectivity, formal logic, and purity.',
        zh: '現代主義',
        zhDef: '以理性的人類主體（笛卡兒「我思故我在」）作為知識與真理來源的世界觀；現代主義藝術重視客觀性、形式邏輯與純粹性。' },
      { en: 'Philosophy of The Subject',
        def: 'The modernist philosophical tradition, rooted in Descartes, that positions the rational, autonomous human subject as the stable center and source of knowledge, meaning, and artistic authorship; postmodernism\'s central target of critique.',
        zh: '主體哲學',
        zhDef: '源自笛卡兒的現代主義哲學傳統，將理性、自主的人類主體，設定為知識、意義與藝術創作權威的穩定中心與來源；此傳統正是後現代主義批判的核心對象。' },
      { en: 'Postmodernism',
        def: 'Not simply "after modernism" but a critical continuation of it; a set of tendencies that both extend and rupture modernist thought and culture.',
        zh: '後現代主義',
        zhDef: '並非單純「在現代主義之後」，而是對現代主義的批判性延續；一組同時延伸並斷裂現代主義思想與文化的傾向。' },
      { en: 'Grand Narrative',
        def: 'Jean-François Lyotard\'s term for the large-scale, unifying stories (e.g., progress, reason, emancipation) that modern societies used to legitimize knowledge and history; postmodernism is often defined precisely as "incredulity toward grand narratives."',
        zh: '宏大敘事',
        zhDef: '李歐塔的用語，指現代社會用以正當化知識與歷史的大規模、統合性故事（例如進步、理性、解放）；後現代主義往往正是被定義為「對宏大敘事的不信任」。' },
      { en: 'Deconstruction vs. Reconstruction (Ihab Hassan)',
        def: 'Hassan\'s two postmodern tendencies: "deconstructive" traits (indeterminacy, fragmentation) that unsettle established order, and "reconstructive" traits (irony, hybridity, participation) that build new forms from the fragments.',
        zh: '解構 vs. 重構（伊哈布·哈山）',
        zhDef: '哈山提出的兩種後現代傾向：「解構性」特質（不確定性、碎片化）動搖既定秩序；「重構性」特質（反諷、混雜性、參與性）則從碎片中建構出新的形式。' },
      { en: 'Neo-Expressionism',
        def: 'An international return to raw, emotionally charged figurative painting (late 1970s–mid-1980s), reacting against the coolness of Minimalism and Conceptual Art.',
        zh: '新表現主義',
        zhDef: '一場國際性的回歸，重返原始、情感強烈的具象繪畫（1970年代晚期至1980年代中期），反抗極簡主義與觀念藝術的冷峻。' },
      { en: 'High And Low Culture',
        def: 'A distinction, foundational to modernist criticism (Greenberg), between serious, elite "high" art and popular, commercial "low" culture; postmodern strategies such as appropriation and Pop Art deliberately blurred or collapsed this hierarchy.',
        zh: '高／低文化',
        zhDef: '現代主義批評（格林伯格）的基礎區分，將嚴肅、菁英的「高級」藝術，與通俗、商業的「低俗」文化區隔開來；後現代的挪用策略與普普藝術，則刻意模糊或瓦解了這種階級劃分。' },
      { en: 'Appropriation',
        def: 'A strategy of taking existing images from art history, advertising, or media and re-presenting or recombining them into new work, without physically collaging the original material.',
        zh: '挪用',
        zhDef: '一種策略，擷取藝術史、廣告或媒體中既有的影像，重新呈現或重組為新的作品，而不進行原始材料的實體拼貼。' },
      { en: 'Feminism',
        def: 'A social and political movement, and body of critical theory, advocating for the equality of the sexes and analyzing how gender shapes power, representation, and cultural production; the direct foundation for feminist art history and activist groups such as the Guerrilla Girls.',
        zh: '女性主義',
        zhDef: '一場社會與政治運動，也是一套批判理論，主張性別平等，並分析性別如何形塑權力、再現與文化生產；是女性主義藝術史及游擊隊女孩等行動主義團體的直接理論基礎。' },
      { en: 'Graffiti Art',
        def: 'Unauthorized image-making in public urban space, originating in 1970s New York; entered the gallery/market system in the early 1980s.',
        zh: '塗鴉藝術',
        zhDef: '未經授權、於公共都市空間中的影像創作，起源於1970年代紐約；於1980年代初進入畫廊／市場體系。' },
      { en: 'Neo-Conceptualism',
        def: 'A cluster of 1970s–80s tendencies critiquing cultural norms (originality, gender) and examining the relationship between capitalism, mass media, and personal identity.',
        zh: '新觀念主義',
        zhDef: '1970至80年代一系列批判文化規範（原創性、性別）、探討資本主義、大眾媒體與個人身分認同之間關係的傾向總稱。' },
      { en: 'Feminist Art History',
        def: 'A field of research, emerging in the early 1970s, focused on recovering women artists, exposing gender bias in art-historical narratives, and examining how gender shapes the making and reception of art.',
        zh: '女性主義藝術史',
        zhDef: '興起於1970年代初的研究領域，聚焦於重新發掘女性藝術家、揭露藝術史敘事中的性別偏見，並探討性別如何形塑藝術的創作與接受。' },
      { en: 'Guerrilla Girls',
        def: 'An anonymous feminist artist collective (founded 1985) that uses gorilla masks, deceased women artists\' pseudonyms, posters, and statistics (e.g., the "Weenie Count") to expose sexism and racism in the art world.',
        zh: '游擊隊女孩',
        zhDef: '一個匿名的女性主義藝術家團體（成立於1985年），運用大猩猩面具、已故女性藝術家的化名、海報與統計數據（例如「小雞雞計數」）來揭露藝術界中的性別歧視與種族歧視。' },
      { en: 'The Weenie Count',
        def: 'A recurring statistic used by the Guerrilla Girls in their poster campaigns, tallying the ratio of nude female figures to works by female artists in major museum collections, to expose the gap between how women are depicted and how rarely they are exhibited.',
        zh: '小香腸計數',
        zhDef: '游擊隊女孩海報宣傳中反覆使用的一項統計數據，計算主要美術館館藏中裸體女性形象與女性藝術家作品的比例，藉此揭露女性「被描繪」與「被展出」之間的巨大落差。' },
      { en: 'The Death of The Author',
        def: 'Roland Barthes\'s 1967 essay arguing that a work\'s meaning should not be fixed by the author\'s intention, but is instead produced anew by each reader or viewer; a key theoretical foundation for postmodern appropriation, which treats existing images as open material for reuse.',
        zh: '作者已死',
        zhDef: '羅蘭·巴特1967年的文章，主張作品的意義不應由作者的意圖所固定，而是由每位讀者或觀者重新產生；此理論是後現代挪用手法的重要基礎，將既有影像視為可開放重新運用的素材。' },
    ]
  },
];
